gomoku: gomoku_main.o gomoku_input.o gomoku_output.o gomoku_judge.o gomoku_validation.o gomoku_sub.o
	gcc gomoku_main.o gomoku_input.o gomoku_output.o gomoku_judge.o gomoku_validation.o gomoku_sub.o -o gomoku

gomoku_main.o: gomoku_main.c
	gcc gomoku_main.c -c

gomoku_input.o: gomoku_input.c
	gcc gomoku_input.c -c

gomoku_output.o: gomoku_output.c
	gcc gomoku_output.c -c

gomoku_judge.o: gomoku_judge.c
	gcc gomoku_judge.c -c

gomoku_validation.o: gomoku_validation.c
	gcc gomoku_validation.c -c

gomoku_sub.o: gomoku_sub.c
	gcc gomoku_sub.c -c
